name: Custom.er
favicon: null
layout_spectrum: 0.47169990348629653
typography_spectrum: 0.7858688808046281
title: Putting the Custom in Customer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15228836610913277
  lightness: 0.8735547559335828
  saturation: 0.15587356314063072
  rhythmicContrast: 0.5499388587195426
purpose: []
